include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_print: false
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    dangling_library_doc_comments: true
    directives_ordering: true
    file_names: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    omit_local_variable_types: false
    prefer_relative_imports: true
    sort_pub_dependencies: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: false